---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-ipin
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      type: cronjob
      cronjob:
        concurrencyPolicy: Forbid
        schedule: "@monthly"
    restartPolicy: OnFailure
    image:
      repository: ghcr.io/onedr0p/kubernetes-kubectl
      tag: 1.26.0@sha256:6ee3353da3495bc99d73af29a4495bb95570e31e71579cfce719c4123882723d
    command: ["/bin/bash", "/app/cloudflare-ipin.sh"]
    envFrom:
      - secretRef:
          name: cloudflare-ipin-secret
    service:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        type: configMap
        name: cloudflare-ipin-configmap
        subPath: cloudflare-ipin.sh
        mountPath: /app/cloudflare-ipin.sh
        defaultMode: 0775
        readOnly: true
