apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:xLR/XlDrjyKiv6cSupq/OKhLyT3yQej1JykthKhCuzC/HlDEXvRHrQ==,iv:8pDKzuHI1LxQQFfd53lXktXFhMm9i/Swz9gRmSm/LRA=,tag:dLTSJABab+YITrLPdE7nLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kxlrmjhl9d384jw7q2md6gucqa2a72f0ajz7anc4fzcepjjz9fuq0af3u3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSjBPSStuY25ZekRKSGZK
            alFZRmJNUlZSSlR5ZFAyUzVyQ2hDRDNFUW5rCmRSRFJZRWkzMjhLR3BiaWEvK01Q
            c1BCOU5jZGoyd2U5YlE4bGIxT0IvUG8KLS0tIHVJTHdpbVM1KzZMa3gyRCtOSjZ2
            T0lJZE96U0puSHJuZm1YOWtzMG9MUWMKdlJwI7E8IHFUiHEYNwTx9yVNvmJyAjO/
            WX3ILRu0MrmWfeQiKoDv0AFgDiJAwcWpDZLwhJXc5wND8SWmrvr3iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T08:09:26Z"
    mac: ENC[AES256_GCM,data:LvkSnIXdipKhYDsYfmmIRqAMQiF+rumE02D1MxX+TbDYSyFYSfGOOBbpCM1vXwxR8jfH8P6v3AikHEKMiiF/wQbpcvyLlD3YmvrPHJDU48DHMkFz5C0e7xHyKuTcIQ0kQUJCHfMOhyDimsWxKFxJCCHHZHjC/u7iZkNgiI0gNR4=,iv:Lc8+1AqPa9cg95ilouCnxLBh516RXpdiNeoKfv3aWpg=,tag:ydnDcjFiqXpgkNeVW/K+hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
