apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:H/IHrgMUSZVGBDc43xoX88YkAgaK0BsyaaHGlS99sC3digsv8g==,iv:D1JEembcdsQpHxWKANi/S6Y2blF5ps2zEgnV+JXFEY4=,tag:tTa7F6C+SyRuro/ChxLg3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kxlrmjhl9d384jw7q2md6gucqa2a72f0ajz7anc4fzcepjjz9fuq0af3u3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTlVjdXVoNzJLSFJETVFL
            emdlYXVrZzNVcmVlNmNlRURhSHBqenkwZ3pRCnc2MVhrdDZWU3NsTm1qL05KR2t6
            amdRNHQ4dkZ0R2dUTnpSRThUbThDL1UKLS0tIGdXd081U3N2NmFRZEF2NHdZeEpZ
            NDZWTTg2SzBxbmNZVk8yK3B4QWRUTVEKsXYpZZnHGLP45+oWyxJSdS3KAAWaj0sH
            fMHK6cbSZlb1Tw7QYH6xYWYl0kpOyvZa1djQ3HrCF8T7H2AmIF5ceA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T08:09:26Z"
    mac: ENC[AES256_GCM,data:od9Mrv8WB2zMa/gpk7wEk56Ep1zdH2fgMnTslOfhX+xgU2+BSkQgpTY8fnf5gpcpXBEFkEPd/afAI8DgmwN4oIVXLwHNkWm28z7Iu93VLFVCgfnKm1NvO18uMvnnvus3m0NyXRol+Bb57+J9JnelSM1YpYpyaeJFUQVsRN1vhGs=,iv:7WSsZR7iZak9A2Gi+7goj/JIW1RjvDlsxhfWo57yhoQ=,tag:rV8T/0XLjPDh6Gd2hOgshQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
