apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:8MT5kWH+MawL55z7CcWDZekN,iv:bLQ8ENC8CND6V817r3GDaPCPXQFVa1iPBBYHuWi7Ec0=,tag:zr5IP0FycRfxqxExrB4IbA==,type:str]
    api-key: ENC[AES256_GCM,data:0neBZBMBsJw2xBFqLEttruYjkoYYE20bZZz/MevC+pWAubqxcg==,iv:/gRxCiZoYQEBF9egGsm5vJ8qrCAcFKl6Wzi6FzBIKS4=,tag:EI1DY0icVZrbaHToyM5quA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kxlrmjhl9d384jw7q2md6gucqa2a72f0ajz7anc4fzcepjjz9fuq0af3u3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZThrS05tT2UvUTZXU3Vw
            NEtDckx1MUJ5eEs3WWx0R0JuY1NhUFY0cDFJCjdRUTg2RWN0TDYyZkNUNDhSREtQ
            WVYyYlQ5RG5EK1UyZVZBYkI1U2dVeVUKLS0tIC84V1Z0N3ZvRzNYeW1TcFRNOGRS
            WTlscUFHTHlVQVAxbmpFTHF5TnFCRzAKIhNHE8EuY5I/UGBl1oXu1eQzTkPIWJuz
            pVG/D02z3fXd4yWnbxSDqhEIvpzkiimTDkhdGYUCw5FPLyms/vnwUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T10:44:54Z"
    mac: ENC[AES256_GCM,data:/TgcOHhC+RlT4TsFiwiLQLtgdg/OPZh8CDyXr7R1Ajl/q7Gpf72CJ3egTljX3CaWIcuO1NLOICdPQ+tlu+2vkVcDdFRjxkjfwcAeDpnzI4z+eM8+lKlpxlIPmXuoCaM+tfpSGXXa95fOQ/5tJ/8pGvh4Eb39BotEAluAtgy+xGc=,iv:lLjgXZ2zNAbWjJCRk/JWlGCpvwjeznxY3eOc7JTVnPg=,tag:+45DlCU9b/RfO5P16uBqdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
