apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:DYPDmDhH3yZRfMccS4OGgc2v,iv:+NAQgfibY78RKHnjwepOOUfyJHluQ2o0cWNxgeSh1AU=,tag:9fz+r+cGBi774qvT/RSEzQ==,type:str]
    api-key: ENC[AES256_GCM,data:LEdTs/aC74RroAWwrFnRJT73EBHMxpC99xPJjEYuc2DrbAtaVw==,iv:S2BG8SZRC+Tpw3QL5hl1OEsLwMxrWFm1ZgehoVdiYR0=,tag:oS1sZ8OyGzHVYTnBitpBIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kxlrmjhl9d384jw7q2md6gucqa2a72f0ajz7anc4fzcepjjz9fuq0af3u3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdmRxTEp4RGE1SnFHZWNn
            dHZsc01KYWRUQUlxUVJQcWVNNktQcHZYMDIwCjdwM2hkVEo3b3dVNHkyKzRUVitn
            SGZScmIxOWtQbWpraWllZ2pLeUhhVlkKLS0tIDJ0Q0h2OFdRYmNZSStjU0M1a2Fk
            MzNOQk9Qb1lJM0hZVG1Xb2R0Nk83UHcKAhfotklZ3gjfweWYUc6lfFENwlS8JfW7
            tM+c7OfZRGAvvq/sponXXjDiSWD/rapJHVqXxjPpJKjQ4Hc4LPdgWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T08:09:26Z"
    mac: ENC[AES256_GCM,data:Lgkt+j86CwRvORR+x95XU/48NniCoCdhgyqoZrQkxRNgIMoEjoJgvq7DRr9pKdKeV8Toje8TImoNZnYH6GrheJHIaFPDlzBJ+c98V+FdM2QWtTk6T7fWL4Jvg+V4c8H7+hm1Qq4DcpOFFYGn06RgFgvYazQykDQ7ATPxI5MRS8Q=,iv:xFBTgFLjk0VVb8kv7KF2wqbbsX60k0k9fEnx70L32EM=,tag:qVM+kVPPrSRa+Df5af9Hlw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
