apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:8S4vcspIXZ4sGfM+dN4yEwPh/eHGP7bLX61/bThzStpbvMszAAXym6HacZhi9GVHT9FvN448vZU25ZPq,iv:f7A0TW9CNSmyc/5ZHHUkCHxw8J3UcypSIJSP2rujY2I=,tag:e8ZLMKsTMPQ294L9LtxtKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kxlrmjhl9d384jw7q2md6gucqa2a72f0ajz7anc4fzcepjjz9fuq0af3u3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZEM5OUJnTHA3S3JrQzJo
            aERLVXB0b3lETnJQbURhMTRveTJIRW9kaTBZCmJJTHZJM2dqOGF0K1FFQ3pLVkxh
            T2I5ano4elR0c25TUXNaWWM2K0dLcGMKLS0tIHI0dC9WalkzL1RsU2JEVEdrWjZa
            Zk13RExTRDNTNlhQNlZkeWZWTmNyZmcKruDZi4eD0AWvk9M49I3z0z0yUAG5w2vL
            LEOC/nMKDzDW6paNh+5OJLRwuP8HInphWyis7kVUz59KMNz3trtv4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T10:44:54Z"
    mac: ENC[AES256_GCM,data:OnJfwbKdsKWfd660cG5yWIylWq867wRI0FejTawZoGaE+s/4xqfRVuBZUlzUw2tuwTQttFol3TPS9V/zB2z3cd/U9baxensPiCGqSh64bbSguekHOiQfHrCXlaifjhL9x1oCsFIg/Cm9F/DcXBYOBuuRFrr9PQh1jK7pEJngP/Y=,iv:7/VRlbJouNm/Rb2eSmwD4q+pu/GmcJG1BSf8E0zYV/Q=,tag:iSUjKdw4KI2i3hJPq47okQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
