apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:cxcBAb6wt5hB5Q==,iv:LFo1nh7YzcnrhNY567MVL7NKcEMw/FtLTUQqqwfonLg=,tag:WbEH0qCiguooC1GUHD2xHA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:+jUZDyXVvAVrncZJRiy58WfF,iv:ItRTSgfOQk4e8l2YzYCGg2eObZsNYfLd1ef6ZOxlQIA=,tag:aIa/TxTFIufT0tuYbZSEEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kxlrmjhl9d384jw7q2md6gucqa2a72f0ajz7anc4fzcepjjz9fuq0af3u3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMHFKcUxWM1BqSCsvMHpH
            VTFuOFZjTVhFNm1oajZheW1SUi9JOElXNEJvCkp4bUp1Z04wdUlsMVhDRlpJVVRm
            L01HUU9wQ2tMbTFlNlpGU3lrWTRnM3MKLS0tIEZBcG1JTnlQWHFud0J3ZlhvSDgy
            QTFFMGM5MGRjVURHZnNqL2RvcUltRVkK7JZQbxkU3ny+9vUpaDXm87ZWaQiPpGdZ
            61OArw4rPFlFTBLe2AmgonSsq1hnm6JubPBV0xPg2JAnNVyy28nqUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T08:09:25Z"
    mac: ENC[AES256_GCM,data:neVQQeNft9zzku/TDOk9VYnoPMlhsVF3OEuJbB+HocYM0XB2UcF7vHH535NpoqjxOMqDyMk87E9n7fE2Nszc3/wZiEnpq28quVogAYtQrRD3amGr0tj1cSjgmwuwrl80Fpv2BNs09J2saYP3LuKLGRecykk/vEaqwzuLYBZAQ64=,iv:UBU14h0mbQfLuTVNRGZkHbo7OHPDNNqMoI74ibsUPNg=,tag:pWDdwBUHtkOqQMmCei55cA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
