---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  KUBE_VIP_ADDR: "192.168.0.30"
  METALLB_LB_RANGE: "192.168.0.36-192.168.0.45"
  METALLB_K8S_GATEWAY_ADDR: "192.168.0.45"
  METALLB_INGRESS_ADDR: "192.168.0.36"
